### PR TITLE
add multi stage dockerfile

### PR DESCRIPTION
**Pull request by niranjan92**

### CODE REVIEW

**Comment by niranjan92** [comment]
@marcusolsson updated dockerfile for multi stage builds. I was unable to build previous image

**Comment by marcusolsson** [comment]
Thanks for the PR! Multi-stage builds seems really cool. Unfortunately, I don't think Travis CI supports multi-stage Docker builds yet? Don't know why the PR hasn't been started on Travis yet, but I'm fairly confident it would fail if merged.

**Comment by marcusolsson** [comment]
Also, I think we should probably migrate from glide to dep which means that we probably could slim down the Dockerfile a bit. Is that something you'd like to include in your PR?

**Comment by niranjan92** [comment]
@marcusolsson : sorry forgot to comment. I had updated my PR to make it compatible with travis. seems okay as the build is green 👍

**Comment by durandom** [comment]
when building locally I get this:

```
❯ docker build .
Sending build context to Docker daemon  9.509MB
Step 1/10 : FROM billyteves/alpine-golang-glide:latest AS build-env
 ---> 8fe5ba9b2f27
Step 2/10 : ADD . /go/src/github.com/marcusolsson/pathfinder
 ---> 68a00b29d6e3
Step 3/10 : RUN cd /go/src/github.com/marcusolsson/pathfinder && glide install
 ---> Running in ec82318db454
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching github.com/go-stack/stack.
[INFO]  --> Fetching github.com/go-kit/kit.
[INFO]  --> Fetching github.com/gorilla/context.
[INFO]  --> Fetching github.com/kr/logfmt.
[INFO]  --> Fetching golang.org/x/net.
[INFO]  --> Fetching github.com/gorilla/mux.
[INFO]  --> Fetching github.com/go-logfmt/logfmt.
[INFO]  Setting references.
[INFO]  --> Setting version for github.com/go-logfmt/logfmt to 538518f3a61c040f3d15f05decfffef6bd0302bc.
[INFO]  --> Setting version for github.com/gorilla/context to 08b5f424b9271eedf6f9f0ce86cb9396ed337a42.
[INFO]  --> Setting version for github.com/go-kit/kit to 6fb874ce59bb45b2f60ee3d289829db02142ecc6.
[INFO]  --> Setting version for github.com/gorilla/mux to 0eeaf8392f5b04950925b8a69fe70f110fa7cbfc.
[INFO]  --> Setting version for github.com/kr/logfmt to b84e30acd515aadc4b783ad4ff83aff3299bdfe0.
[INFO]  --> Setting version for github.com/go-stack/stack to 100eb0c0a9c5b306ca2fb4f165df21d80ada4b82.
[INFO]  --> Setting version for golang.org/x/net to 55a3084c9119aeb9ba2437d595b0a7e9cb635da9.
[INFO]  Exporting resolved dependencies...
[INFO]  --> Exporting github.com/go-kit/kit
[INFO]  --> Exporting github.com/go-logfmt/logfmt
[INFO]  --> Exporting github.com/gorilla/context
[INFO]  --> Exporting github.com/kr/logfmt
[INFO]  --> Exporting github.com/gorilla/mux
[INFO]  --> Exporting github.com/go-stack/stack
[INFO]  --> Exporting golang.org/x/net
[INFO]  Replacing existing vendor dependencies
 ---> 9095c767d21f
Removing intermediate container ec82318db454
Step 4/10 : RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o pathfinder .
 ---> Running in 7953329a4061
can't load package: package app: no buildable Go source files in /go/src/app
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o pathfinder .' returned a non-zero code: 1
```

any ideas?

**Pull request merged**
